version: '3.8'

services:
  database:
    image: mariadb:10.11
    container_name: fitness_ws
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fitness_db
      MYSQL_USER: fitness_user
      MYSQL_PASSWORD: fitness_password
    ports:
      - "3306:3306"
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
      - fitness_db_data:/var/lib/mysql

volumes:
  fitness_db_data: